# action.yml
name: 'Repomerge'
description: 'Pushes repo to a specific branch in another repo'
branding:
  icon: 'package'
  color: 'blue'
author: 'Jonas Otto @ottojo'
inputs:
  destination:
    description: 'Destination Repo (Format: github.com/ottojo/combined-test.git, without "https://")'
    required: true
    default: 'github.com/ottojo/combined-test.git'
  pat:
    description: 'Personal Access Token (needs repo permissions)'
    required: true
    default: ''
  branch:
    description: 'Name of branch in destination repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination }}
    - ${{ inputs.pat }}
    - ${{ inputs.branch }}
